name:                bitpack-safe
version:             0.1.0.0
github:              "Fuuzetsu/bitpack-safe"
license:             BSD3
author:              "Mateusz Kowalczyk"
maintainer:          "fuuzetsu@fuuzetsu.co.uk"
copyright:           "2019 Mateusz Kowalczyk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Fuuzetsu/bitpack-safe#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  bitpack-safe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bitpack-safe
